Fix clang error.
roboptim-core/tests/simple.cc:112:17: error: reference cannot be bound
  to dereferenced null pointer in well-defined C++ code; comparison may
  be assumed to always evaluate to true [-Werror,-Wtautological-undefined-compare]
  BOOST_CHECK (&pb.constraints ()[0] != 0);